language: cpp

os:
  - linux
  - osx
  
compiler:
  - gcc
  - clang

before_install:
  # Get libs for OSX
  - "if [ $TRAVIS_OS_NAME = 'osx' ]; then brew update; fi"
  #- "if [ $TRAVIS_OS_NAME = 'osx' ]; then brew tap homebrew/science; fi"
  #- "if [ $TRAVIS_OS_NAME = 'osx' ]; then brew install opencv3; fi"
  - "if [ $TRAVIS_OS_NAME = 'osx' ]; then brew install libxml2 libdc1394 gsl; fi"
  
  # Get libs for Linux
  - "if [ $TRAVIS_OS_NAME = 'linux' ]; then sudo apt-get update -qq; fi"
  - "if [ $TRAVIS_OS_NAME = 'linux' ]; then sudo apt-get install -qq cmake libopencv-dev libx11-dev; fi"
  - "if [ $TRAVIS_OS_NAME = 'linux' ]; then sudo apt-get install -qq liblapack-dev libgsl0-dev; fi"
  - "if [ $TRAVIS_OS_NAME = 'linux' ]; then sudo apt-get install -qq libdc1394-22-dev libv4l-dev; fi"
  - "if [ $TRAVIS_OS_NAME = 'linux' ]; then sudo apt-get install -qq libcoin60-dev; fi"
  - "if [ $TRAVIS_OS_NAME = 'linux' ]; then sudo apt-get install -qq libxml2-dev; fi"
  - "if [ $TRAVIS_OS_NAME = 'linux' ]; then sudo apt-get install -qq libjpeg-dev libpng12-dev; fi"
  - "if [ $TRAVIS_OS_NAME = 'linux' ]; then sudo apt-get install -qq libswscale-dev libavutil-dev; fi"
  - "if [ $TRAVIS_OS_NAME = 'linux' ]; then sudo apt-get install -qq libavformat-dev; fi"
  - "if [ $TRAVIS_OS_NAME = 'linux' ]; then sudo apt-get install -qq libavcodec-dev libbz2-dev; fi"
  - "if [ $TRAVIS_OS_NAME = 'linux' ]; then sudo apt-get install -qq libogre-dev libois-dev; fi"
  - "if [ $TRAVIS_OS_NAME = 'linux' ]; then sudo apt-get install -qq libzbar-dev libdmtx-dev; fi"

before_script:
  - mkdir build
  - cd build
  - cmake ..

script: make

notifications:
  email:
    - Fabien.Spindler@inria.fr
  on_success: change
  on_failure: always
   
