# Specify version format
version: "3.2.0-{build}"

image:
  - Visual Studio 2017

# to add several platforms to build matrix
platform:
  - x64

configuration:
  - Release

environment:
  VISP_OPENCV_MINGW_FILE: opencv-3.3.0-MinGW-build-package.7z
  VISP_OPENCV_MINGW_DIR: opencv-3.3.0-MinGW-build-package
  VISP_OPENCV_MINGW_PKG: https://github.com/s-trinh/visp-dependencies/blob/master/opencv-3.3.0-MinGW-build-package.7z?raw=true
  VISP_OPENCV_VS2015_2017_FILE: opencv-4.0.0-beta-vc14_vc15.exe
  VISP_OPENCV_VS2015_2017_DIR: opencv-4.0.0-beta-vc14_vc15
  VISP_OPENCV_VS2015_2017_PKG: https://github.com/opencv/opencv/releases/download/4.0.0-beta/opencv-4.0.0-beta-vc14_vc15.exe

  matrix:
    #- CMAKE_GENERATOR: MinGW Makefiles
    #  BUILD_NAME: mingw

    - CMAKE_GENERATOR: Visual Studio 15 2017 Win64
      BUILD_NAME: vs2017

# Scripts that are called at very beginning, before repo cloning
init:
  - cmake --version
  - msbuild /version

install:
  # Create temp dir to collect test outputs
  - md C:\temp

  # All external dependencies are installed in C:\projects\deps
  - mkdir C:\projects\deps
  - cd C:\projects\deps

  # visp-images
  - git clone --depth 1 https://github.com/lagadic/ViSP-images C:\projects\deps\ViSP-images
  - set VISP_INPUT_IMAGE_PATH=C:\projects\deps

on_finish:
  - ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
